// <auto-generated />
namespace PSIMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class stockreturndetails_status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stockreturndetails_status));
        
        string IMigrationMetadata.Id
        {
            get { return "202102031748134_stockreturndetails_status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
